# Generated by Django 2.2.9 on 2019-12-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
