# Generated by Django 2.2.9 on 2020-01-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreviewWork',
        ),
    ]
