# Generated by Django 2.2.9 on 2020-01-02 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_previewworks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreviewWorks',
            new_name='PreviewWork',
        ),
    ]
