# Generated by Django 2.2.9 on 2020-01-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_viewed',
            field=models.BooleanField(default='False'),
        ),
    ]
