# Generated by Django 2.2.9 on 2020-02-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_work_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_alive',
            field=models.BooleanField(default='True'),
        ),
    ]
