# Generated by Django 2.2.9 on 2020-02-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_request_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='category',
        ),
        migrations.AddField(
            model_name='request',
            name='category_id',
            field=models.IntegerField(default=0),
        ),
    ]
